name: alcoholdeliver
description: "Alcohol Deliver mobile app develop by gadgetvala"
publish_to: "none"
version: 4.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"
  flutter: ^3.19.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  pin_code_fields: ^8.0.1
  auto_size_text: ^3.0.0
  dio: ^4.0.6
  flutter_riverpod: ^2.4.0
  connectivity_plus: ^6.0.2
  shimmer: ^3.0.0
  shared_preferences: ^2.2.1
  cached_network_image: ^3.2.3
  fluttertoast: ^8.2.2
  image_picker: ^1.0.7
  file_picker: ^8.0.0+1
  device_info_plus: ^10.1.0
  path_provider: ^2.1.1
  onesignal_flutter: ^5.1.6
  uuid: ^4.4.0
  firebase_core: ^3.3.0
  firebase_database: ^11.0.4
  firebase_crashlytics: ^4.0.4
  web_socket_channel: ^3.0.1
  flutter_keyboard_visibility: ^6.0.0
  firebase_messaging: ^15.0.4
  flutter_local_notifications:
  timezone: ^0.9.4
  lottie: ^3.1.2
  bugsee_flutter: ^8.2.1

  # Locations
  google_maps_flutter: ^2.6.1
  flutter_polyline_points: ^2.0.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  location: ^7.0.0
  permission_handler: ^11.3.1

  # Background Service
  background_locator_2: ^2.0.6
  flutter_typeahead: ^5.2.0
  photo_view: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_logo_3.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/json/

  fonts:
    - family: AbrilFatface
      fonts:
        - asset: assets/fonts/AbrilFatface-Regular.ttf
          weight: 400
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
