// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOqghNt66cAxDNJks-yeo2U4Z3JNPA3GI',
    appId: '1:582469330775:android:10db67febb08f66f42c012',
    messagingSenderId: '582469330775',
    projectId: 'alcohol-delivery-app-7120d',
    databaseURL: 'https://alcohol-delivery-app-7120d-default-rtdb.firebaseio.com',
    storageBucket: 'alcohol-delivery-app-7120d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSBR1mlrGlYhBqqrlTq54bpC_Ao-JtZeY',
    appId: '1:582469330775:ios:0fa0cc091e86955542c012',
    messagingSenderId: '582469330775',
    projectId: 'alcohol-delivery-app-7120d',
    databaseURL: 'https://alcohol-delivery-app-7120d-default-rtdb.firebaseio.com',
    storageBucket: 'alcohol-delivery-app-7120d.appspot.com',
    iosBundleId: 'com.example.order',
  );
}
